import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Provider } from "react-redux"; // Import Redux Provider
import store from "@/store/store"; // Import your Redux store
import ProtectedRoute from "@/components/ProtectedRoute"; // Import ProtectedRoute
import ClientProvider from "@/components/ClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProvider> 
          <Header />
          
          <ProtectedRoute>
            {children}
          </ProtectedRoute>

        </ClientProvider>
      </body>
    </html>
  );
}
